### ISSUE TITLE
NoMethodError - undefined method `attributes_hash' for nil:NilClass

### ISSUE THREAD

**Issue by jimmyken** [CocoaPods/cocoapods-packager#114]
### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.1 (15B42)
       Xcode : 7.1.1 (7B1005)
         Git : git version 2.4.9 (Apple Git-60)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories : master - https://gitcafe.com/akuandev/Specs.git @ 90b0956a701784b8520b76ac72aa84ed8bba69f3
```

### Plugins

```
cocoapods-packager : 1.3.0
cocoapods-plugins  : 0.4.2
cocoapods-search   : 0.1.0
cocoapods-stats    : 0.6.2
cocoapods-trunk    : 0.6.4
cocoapods-try      : 0.5.1
```

### Error

```
NoMethodError - undefined method `attributes_hash' for nil:NilClass
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.3.0/lib/cocoapods-packager/pod_utils.rb:61:in `block (2 levels) in binary_only?'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.3.0/lib/cocoapods-packager/pod_utils.rb:60:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.3.0/lib/cocoapods-packager/pod_utils.rb:60:in `block in binary_only?'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.3.0/lib/cocoapods-packager/pod_utils.rb:59:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.3.0/lib/cocoapods-packager/pod_utils.rb:59:in `binary_only?'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:45:in `validate!'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:311:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by neonichu** [comment]
Could you please share the podspec you are trying to package?

**Comment by neonichu** [comment]
Closing because of lack of response.

**Comment by kwinegardner** [comment]
I'm getting this as well -

New system setup:
Mac: Sierra 10.12.1
Xcode: Version 8.1 (8B62)
ruby: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

cocoapods-deintegrate : 1.0.1
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0

All I have installed is Xcode, cocoapods and cocoapods-packager

It feels to me like something else needs to be installed in order for this to run correctly...
