### ISSUE TITLE
error:  cocoapods-packager, s.dependency is private pod (no github)

### ISSUE THREAD

**Issue by XZoscar** [CocoaPods/cocoapods-packager#143]
pod package my.spec ( spec.dependency 'MyBase', '~> 1.0.0' )  --spec-sources=private
```
### Error
```
NoMethodError - undefined method `attributes_hash' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.4.0/lib/cocoapods-packager/pod_utils.rb:82:in `block (2 levels) in binary_only?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.4.0/lib/cocoapods-packager/pod_utils.rb:81:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.4.0/lib/cocoapods-packager/pod_utils.rb:81:in `block in bin
---
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.4.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0

**Comment by XZoscar** [comment]
使用pod package 自动打framework,
当spec中s.dependency为私有的MyBase时，报错了
然而，使用github上的一个spec文件（具有s.dependency）是OK的

**Comment by neonichu** [comment]
Could you please share your podspec?

**Comment by aolan** [comment]
XZoscar , 你的问题解决了吗

**Comment by aolan** [comment]
@XZoscar   你的问题解决了吗

**Comment by aolan** [comment]
@XZoscar  你的问题解决了吗

**Comment by Feng999** [comment]
No updates?

**Comment by rockwotj** [comment]
> Could you please share your podspec?

@neonichu I hit this error when trying to do this with `React-Core` from https://github.com/facebook/react-native/blob/main/React-Core.podspec

**Comment by victorrabelozup** [comment]
No news?
