### ISSUE TITLE
Creating a dynamic framework fails

### ISSUE THREAD

**Issue by michaelochs** [CocoaPods/cocoapods-packager#166]
### Command

```
/Users/michael/.rbenv/versions/2.2.2/bin/pod package ViewDeck.podspec --dynamic
```

### Report

* What did you do?
Really just run the above command on a newly published pod version (ViewDeck 3.0.0)

* What did you expect to happen?
A dynamic framework should have been created from the ViewDeck pod

* What happened instead?
This template was created and the error '[!] Oh no, an error occurred.' was shown.

Note that the command works without issues if I drop the `--dynamic` option.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
    RubyGems : 2.4.5
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/michael/.rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3c4f03d992a242c59537390be44cb337aefcff22
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-packager    : 1.4.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Error

```
NameError - uninitialized constant Pod::Installer::FileReferencesInstaller
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:168:in `const_missing'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.4.0/lib/cocoapods-packager/pod_utils.rb:209:in `install_file_references'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.4.0/lib/cocoapods-packager/pod_utils.rb:146:in `install_dynamic_pod'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.4.0/lib/pod/command/package.rb:80:in `build_in_sandbox'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.4.0/lib/pod/command/package.rb:97:in `block in build_package'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.4.0/lib/pod/command/package.rb:96:in `each'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.4.0/lib/pod/command/package.rb:96:in `build_package'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-packager-1.4.0/lib/pod/command/package.rb:63:in `run'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/michael/.rbenv/versions/2.2.2/bin/pod:23:in `load'
/Users/michael/.rbenv/versions/2.2.2/bin/pod:23:in `<top (required)>'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/michael/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/Users/michael/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/Users/michael/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
```

**Comment by segiddins** [comment]
Out of curiosity, does it work with older CocoaPods versions? If so, we probably just need to cut a new version that adds compatibility with 1.1. (This is one of the dangers of relying on non-public interfaces 😬)

**Comment by michaelochs** [comment]
I used that a lot in previous versions but had issues now and then since 1.0. But these got fixed in the past.

**Comment by segiddins** [comment]
Then I'm guessing this is just a 1.1 compatibility issue with classes being re-namespaced
