### ISSUE TITLE
Show error message if specified pod is a valid file but not a valid pod/podspec

### ISSUE THREAD

**Issue by mickeyreiss** [CocoaPods/cocoapods-packager#22]
`pod package path/to/directory` or `pod package path/to/random/file` both result in a stack trace.

For a directory:

```
Errno::EISDIR - Is a directory @ io_fread - [...]my-pod/
[...].rvm/gems/ruby-2.1.1@my-pod/gems/cocoapods-core-0.33.1/lib/cocoapods-core/specification.rb:491:in `read'
[...].rvm/gems/ruby-2.1.1@my-pod/gems/cocoapods-core-0.33.1/lib/cocoapods-core/specification.rb:491:in `block in from_file'
[...].rvm/gems/ruby-2.1.1@my-pod/gems/cocoapods-core-0.33.1/lib/cocoapods-core/specification.rb:491:in `open'
[...].rvm/gems/ruby-2.1.1@my-pod/gems/cocoapods-core-0.33.1/lib/cocoapods-core/specification.rb:491:in `from_file'
[...].rvm/gems/ruby-2.1.1@my-pod/bundler/gems/cocoapods-packager-f121921d2165/lib/pod_utils.rb:44:in `spec_with_path'
[...].rvm/gems/ruby-2.1.1@my-pod/bundler/gems/cocoapods-packager-f121921d2165/lib/pod/command/package.rb:27:in `initialize'
[...].rvm/gems/ruby-2.1.1@my-pod/gems/claide-0.6.1/lib/claide/command/parser.rb:24:in `new'
[...].rvm/gems/ruby-2.1.1@my-pod/gems/claide-0.6.1/lib/claide/command/parser.rb:24:in `parse'
[...].rvm/gems/ruby-2.1.1@my-pod/gems/claide-0.6.1/lib/claide/command/parser.rb:20:in `parse'
[...].rvm/gems/ruby-2.1.1@my-pod/gems/claide-0.6.1/lib/claide/command.rb:288:in `parse'
[...].rvm/gems/ruby-2.1.1@my-pod/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:39:in `parse'
[...].rvm/gems/ruby-2.1.1@my-pod/gems/claide-0.6.1/lib/claide/command.rb:276:in `run'
[...].rvm/gems/ruby-2.1.1@my-pod/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:48:in `run'
[...].rvm/gems/ruby-2.1.1@my-pod/gems/cocoapods-0.33.1/bin/pod:33:in `<top (required)>'
[...].rvm/gems/ruby-2.1.1@my-pod/bin/pod:23:in `load'
[...].rvm/gems/ruby-2.1.1@my-pod/bin/pod:23:in `<main>'
[...].rvm/gems/ruby-2.1.1@my-pod/bin/ruby_executable_hooks:15:in `eval'
[...].rvm/gems/ruby-2.1.1@my-pod/bin/ruby_executable_hooks:15:in `<main>'
```

For a file that is not a podspec:

```
➜  my-pod git:(master@3.1.0) ✗ pod package ~/my-pod/CHANGELOG.md
[!] Unsupported specification format `.md`.
[...].rvm/gems/ruby-2.1.1@my-pod/gems/claide-0.6.1/lib/claide/command.rb:304:in `handle_exception': undefined method `verbose?' for nil:NilClass (NoMethodError)
        from [...].rvm/gems/ruby-2.1.1@my-pod/gems/claide-0.6.1/lib/claide/command.rb:284:in `rescue in run'
        from [...].rvm/gems/ruby-2.1.1@my-pod/gems/claide-0.6.1/lib/claide/command.rb:274:in `run'
        from [...].rvm/gems/ruby-2.1.1@my-pod/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:48:in `run'
        from [...].rvm/gems/ruby-2.1.1@my-pod/gems/cocoapods-0.33.1/bin/pod:33:in `<top (required)>'
        from [...].rvm/gems/ruby-2.1.1@my-pod/bin/pod:23:in `load'
        from [...].rvm/gems/ruby-2.1.1@my-pod/bin/pod:23:in `<main>'
        from [...].rvm/gems/ruby-2.1.1@my-pod/bin/ruby_executable_hooks:15:in `eval'
        from [...].rvm/gems/ruby-2.1.1@my-pod/bin/ruby_executable_hooks:15:in `<main>'
```

I'd expect these cases to result in an error message with usage instructions.

**Comment by adilJamshad** [comment]
Hi,

I am facing this error in a react native project that I cloned from github.

Will you share any work around it?
