### ISSUE TITLE
ArgumentError - wrong number of arguments (given 3, expected 7..9)

### ISSUE THREAD

**Issue by zoyag** [CocoaPods/cocoapods-packager#242]
### Command

```
/usr/local/bin/pod package WLTSDK.podspec --force --dynamic --no-mangle
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?
The current version on gem is still failed?  
As I see #236 #222 says it has solved.

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.3 (10G8)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ebc4b9650ffa9062ab7abed05e7759f0482f9a6a
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Error

```
ArgumentError - wrong number of arguments (given 3, expected 7..9)
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/target/pod_target.rb:83:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/pod_utils.rb:161:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/pod_utils.rb:161:in `build_dynamic_target'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/pod_utils.rb:131:in `install_dynamic_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:83:in `build_in_sandbox'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:100:in `block in build_package'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:99:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:99:in `build_package'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:66:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by zoyag** [comment]
need to update the version on gem?

**Comment by zhouQ-job** [comment]
I have encountered such a problem, can you solve it?

**Comment by amorde** [comment]
Yup this was fixed in https://github.com/CocoaPods/cocoapods-packager/pull/240, but it hasn't been released yet. You can use Bundler to pull from master until its released
