### ISSUE TITLE
动态库打包报错：参数数量错误

### ISSUE THREAD

**Issue by zyfrog** [CocoaPods/cocoapods-packager#245]
***ArgumentError - wrong number of arguments (given 3, expected 7..9)***

### Command
```
/usr/local/bin/pod package XXX.podspec --force --dynamic --bundle-identifier=com.xxx.xxxx --no-mangle --spec-sources=private --verbose --configuration=Release
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
ArgumentError - wrong number of arguments (given 3, expected 7..9)
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/target/pod_target.rb:86:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/pod_utils.rb:161:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/pod_utils.rb:161:in `build_dynamic_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/pod_utils.rb:131:in `install_dynamic_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:83:in `build_in_sandbox'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:100:in `block in build_package'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:99:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:99:in `build_package'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:66:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by shshjing** [comment]
本地更新一下cocoapods-packager
https://www.jianshu.com/p/cee6c71b43a3

**Comment by 0x5e** [comment]
#240

**Comment by changwuguo** [comment]
Me too

**Comment by zhonglaoban** [comment]
same problem
