### ISSUE TITLE
Fail to build a pod into dynamic framework

### ISSUE THREAD

**Issue by vitonzhangtt** [CocoaPods/cocoapods-packager#257]
### Command

```
/usr/local/lib/ruby/gems/2.7.0/bin/pod package AFNetworking.podspec --dynamic --no-mangle
```

### Report

* What did you do?

Run the following commands: 
```
$ git clone https://github.com/AFNetworking/AFNetworking.git
$ git checkout tags/4.0.0 -b branch_4.0.0
$ pod package AFNetworking.podspec --dynamic --no-mangle
```

* What did you expect to happen?
After `$ pod package AFNetworking.podspec --dynamic --no-mangle`, a framework will be built. 

* What happened instead?
An error occurred.

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.7 (11E801a)
         Git : git version 2.22.0
Ruby lib dir : /usr/local/Cellar/ruby/2.7.0/lib
Repositories :  
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
claide-plugins                   : 0.9.2
cocoapods-binary                 : 0.4.4
cocoapods-deintegrate            : 1.0.4
cocoapods-dependencies           : 1.3.0
cocoapods-packager               : 1.5.0
cocoapods-plugins                : 1.0.0
cocoapods-rome                   : 1.0.1
cocoapods-search                 : 1.0.0
cocoapods-static-swift-framework : 0.5
cocoapods-stats                  : 1.1.0
cocoapods-trunk                  : 1.5.0
cocoapods-try                    : 1.2.0
```

### Error

```
ArgumentError - wrong number of arguments (given 3, expected 7..10)
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/target/pod_target.rb:137:in `initialize'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/pod_utils.rb:161:in `new'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/pod_utils.rb:161:in `build_dynamic_target'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/pod_utils.rb:131:in `install_dynamic_pod'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:83:in `build_in_sandbox'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:100:in `block in build_package'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:99:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:99:in `build_package'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:66:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/2.7.0/bin/pod:24:in `load'
/usr/local/lib/ruby/gems/2.7.0/bin/pod:24:in `<main>'
```

**Comment by vitonzhangtt** [comment]
@segiddins

If i am @ the wrong person, I'm sorry about that.

Look at the master branch, the calling to `Pod::PodTarget.new` has changed. 
When we will get a version, maybe 1.6.0? 

https://github.com/CocoaPods/cocoapods-packager/blob/f95c6c2322614abb8e3085d7dfa01d4695db3178/lib/cocoapods-packager/pod_utils.rb#L161

**Comment by segiddins** [comment]
@vitonzhangtt we'd be happy to review a PR updating to the latest version of CocoaPods!

**Comment by vitonzhangtt** [comment]
> @vitonzhangtt we'd be happy to review a PR updating to the latest version of CocoaPods!

@segiddins 

As a newbie in Ruby, I would like to know that whether a template for PR in this repo. For example, description for PR, test case for PR and any others.

Cocoapods is a cool tools for iOS daily development. As a iOS developer I would like to contribute my time to these projects.

To be honest, if there are more wiki about `how to debug this gem`, and `how to contribute to this project`, I will save more my time to make PR.
