### ISSUE TITLE
undefined method `module_map' when packaging Pod library

### ISSUE THREAD

**Issue by virl** [CocoaPods/cocoapods-packager#88]
I've created simple Pod library project as described here: https://guides.cocoapods.org/making/using-pod-lib-create

When I "run pod package MyPod.podspec", I receive following error:
```
NoMethodError - undefined method `module_map' for #<Pod::Specification name="MyPod">
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.2.0/lib/cocoapods-packager/builder.rb:118:in `copy_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.2.0/lib/cocoapods-packager/builder.rb:34:in `build_framework'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.2.0/lib/cocoapods-packager/builder.rb:16:in `build'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.2.0/lib/pod/command/package.rb:127:in `perform_build'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.2.0/lib/pod/command/package.rb:71:in `build_in_sandbox'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.2.0/lib/pod/command/package.rb:84:in `block in build_package'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.2.0/lib/pod/command/package.rb:83:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.2.0/lib/pod/command/package.rb:83:in `build_package'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.2.0/lib/pod/command/package.rb:56:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
@virl you'll need to update CocoaPods to something >= 0.37

**Comment by virl** [comment]
@segiddins thanks, it helped.
